### ISSUE TITLE
[Enhancement] Would it be possible to add Overflow capability to PivotBar?

### ISSUE THREAD

**Issue by mikezimm** [n8design/htwoo#11]
Hi,
One of the biggest challenges I have with using Fluent UI in SPFx projects is lack of responsive design in the Pivot compnent.

https://lab.n8d.studio/htwoo/htwoo-core/?p=molecules-pivotbar

Here's an example of my current webpart which allows for a rather lengthy set of pivot buttons.

Also complicating my implementation is that I also need to have a "farRight" set of buttons that float to the right which are not part of the pivot but that's another issue altogether which I think could be implemented with a css grid.

Right now, if I load this on an ipad, I can't even get to my farRight buttons :(

![image](https://user-images.githubusercontent.com/49648086/116645691-54c50380-a944-11eb-8be7-0e3da1213472.png)

Thanks!

**Comment by StfBauer** [comment]
@mikezimm Sorry it took a while but I am happy to announce that overflow control should now work on [pivotbar](https://lab.n8d.studio/htwoo/htwoo-core/?p=molecules-pivotbar-overflow) and [Command Bars](https://lab.n8d.studio/htwoo/htwoo-core/?p=molecules-cmdbar-overflow)

You need to register the overflow.js on the page.

```javascript
import * as overflow from './overflow.js'

const afterLoaded = () => {
    overflow.init();
}

window.onload = afterLoaded()
```

Also, check out the patterns mentioned above. This should give you an indication of what you need to do to have all classes in place.

**Comment by mikezimm** [comment]
@StfBauer , by chance is there any example or blog post (even from someone else) on how to use an HTWOo component in a react based spfx webpart?

I would like to branch out because of many reasons why you created this alternative.

Unfortunately, I am self-trained weekend-developer so I learn by following an example.  Once I have a working sample I can expand and replicate it elsewhere.  I just am pretty shy of 3rd party libraries because early on I tried using one and spent a lot of time frustrated.

If there is one sample of a component built in React for SPFx, I would probably be able to contribute other working components.  I just have trouble getting started.

Thanks again, I really look forward to try this out.

**Comment by StfBauer** [comment]
@mikezimm there are some how-to available on the [documentation page](https://lab.n8d.studio/htwoo/how-to/how-to-spfx-react.html). Have you checked those out. Also, there is a [sample](https://github.com/n8design/htwoo-samples) repo that helps you get started.

**Comment by mikezimm** [comment]
Thanks for the pointer to the react sample.  It looks pretty straight forward so I will give it a try.
