### ISSUE TITLE
Wrong label alignment when using hoo-mtag as <button>

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#110]
**Describe the bug**
When using the `hoo-mtag` component on a `<button>` tag, the label is not aligned as expected.

**To Reproduce**
1. Open [Tag Link in Pattern Lab](https://lab.n8d.studio/htwoo/htwoo-core/?p=atoms-tag-link)
2. Use DevTools to change the `<a>` tag to `<button>` tag

**Expected behavior**
Label alignment should not move.

**Desktop**
 - OS: Windows 10
 - Browser: Edge
 - Version: 121

**Additional context**
Not sure if `hoo-mtag` is meant to support `<button>` but I saw some `button` selector when debugging this.

**Comment by StfBauer** [comment]
It was not an alignment issue it was casue by different fonts. Thanks for reporting this.
