### ISSUE TITLE
Error Label missing from Pattern Lab

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#111]
**Describe the bug**
I am pretty sure there used to be an example for error labels.

**To Reproduce**
1. Go to https://lab.n8d.studio/htwoo/htwoo-core/?p=atoms-error
2. 404 error :(

> Oh snap, a 404!
> You might want to double-check to see if the page you're looking for has moved or if your URL is correct.
> 
> Alternatively, [click here](https://lab.n8d.studio/styleguide/html/styleguide.html) to head back to the default Pattern Lab page!

**Expected behavior**
There should be an example for Error Label, like there is for Success Label.

**Comment by StfBauer** [comment]
Turned out it was a problem with the naming - 

https://lab.n8d.studio/htwoo/htwoo-core/?p=atoms-failed
