### ISSUE TITLE
Height of hoo-input-text changes when focused

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#119]
**Describe the bug**
When focusing a `hoo-input-text` input it get slightly higher, pushing down content below.

**To Reproduce**
1. Go to [Pattern Lab](https://lab.n8d.studio/htwoo/htwoo-core/?p=atoms-input-text)
2. Use DevTools to add a `<p>` or something below the input
3. Focus the input
4. Notice the text below being pushed down a bit.

**Expected behavior**
Size of focused element should not change

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 122

**Additional context**
You can workaround the bug by changing:

```
.hoo-input-text:focus {
    line-height: calc(1.9rem - 2px);
}
```

to:

```
.hoo-input-text:focus {
    /* Base line-height on same as .hoo-input-text (without focus) selector */
    line-height: calc(1.875rem - 2px);
}
```

**Comment by StfBauer** [comment]
Thank you for that.

**Comment by StfBauer** [comment]
Fixed in in 2.4. 0

**Comment by StfBauer** [comment]
Yeah not changing anything at this point in favor of going to Fluent 2.

**Comment by gabbsmo** [comment]
Ok I understand. Noticed a few regressions in invalid fields and the search box so updated my code snippet to account for that.
