### ISSUE TITLE
Forms and dialogs not adapting to dark mode

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#129]
**Describe the bug**
Some styles are not adapting in a good way when enabling the Teams Dark theme.

**To Reproduce**
Test in Pattern Lab:

- Text input
- Radio buttons
- Checkboxes
- Dialogs/Sidebars
- Searchbox

**Expected behavior**
Look and feel should be more similar to the dark theme in New Teams. Though I realize it cannot match 100% until htwoo moves to Fluent 2.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 123

**Additional context**
Added the following CSS to my project which was a huge improvement
```
.hoo-input-text,
.hoo-input-search .hoo-icon,
.hoo-dlg,
.hoo-checkbox + label:before,
.hoo-radio:checked + label:before, .hoo-radio:not(:checked) + label:before {
    background: var(--bodyBackground);
    color: var(--bodyText);
}

.hoo-input-search .hoo-icon {
    fill: var(--bodyText);
}

.hoo-input-text::placeholder {
    color: var(--neutralSecondary);
}
```

**Comment by StfBauer** [comment]
🛳️ Shipped in 2.5.0 - https://lab.n8d.studio/htwoo/changelog/htwoo-core-cl/
