### ISSUE TITLE
Should hoo-nav-list be green in the Teams themes?

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#130]
**Describe the bug**
The accent color seem to be green in all the three Teams themes.

For the SharePoint themes it seem to match the primary color.

**To Reproduce**
1. Go to [Pattern Lab](https://lab.n8d.studio/htwoo/htwoo-core/?p=molecules-nav)
2. Compare the different themes

**Expected behavior**
The accent color (i.e. link text and the right border for current page) should be purple I guess.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 123

**Additional context**
Just let me know if this is by design.

**Comment by StfBauer** [comment]
🛳️ Shipped in 2.5.0 - https://lab.n8d.studio/htwoo/changelog/htwoo-core-cl/
