### ISSUE TITLE
Search box icon border not aligned

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#132]
**Describe the bug**
Depending on DPI, zoom etc. the borders of the search box's icon and input are not always aligned

**To Reproduce**
1. Go to [Pattern Lab](https://lab.n8d.studio/htwoo/htwoo-core/?p=atoms-searchbox)
2. Zoom using the browser

**Expected behavior**
The borders should always be aligned.

**Screenshots**
![image](https://github.com/n8design/htwoo/assets/1475256/6b9e6421-c7d8-4ad1-b800-b1e410fbf901)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 124

**Additional context**
This seem to be a rounding error. The icon is always 32px in height, while the input is 31.44 in my case. A workaround is to use `height: 2rem` for the input, rather than `height: fit-content`.

**Comment by StfBauer** [comment]
🛳️ Shipped in 2.5.0 - https://lab.n8d.studio/htwoo/changelog/htwoo-core-cl/
