### ISSUE TITLE
Background missing from hoo-progress?

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#134]
**Describe the bug**
There seem to be missing a background (or rails or track if you will) for the progress bar.

**To Reproduce**
Steps to reproduce the behavior
1. Go to [Pattern Lab](https://lab.n8d.studio/htwoo/htwoo-core/?p=atoms-loading)

**Expected behavior**
There should be a background, like in [Fluent React](https://developer.microsoft.com/en-us/fluentui#/controls/web/progressindicator).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 124

**Additional context**
My workaround:

```
.hoo-progress {
    background: var(--bodyDivider);
}
```

**Comment by StfBauer** [comment]
🛳️ Shipped in 2.5.0 - https://lab.n8d.studio/htwoo/changelog/htwoo-core-cl/
