### ISSUE TITLE
Button font-family missing from dist/htwoo.min.css

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#140]
**Describe the bug**
I noticed that buttons was using Arial in my project from the user agent style. Could not reproduce in Pattern Lab but found that the style fixing it was in style.scss.

**To Reproduce**
1. Use htwoo.min.css, rather than compiling the SASS yourself.

**Expected behavior**
Buttons should have same font-family as in Pattern Lab.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 125

**Additional context**
I have added the following after htwoo.min.css in my project: 
```
body {
    font-family: var(--mediumFontFamily);
    background-color: var(--bodyBackground);
    color: var(--bodyText);
    margin: 0;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

button[class^='hoo'],
input[class^='hoo'],
textarea[class^='hoo'] {
    font-family: inherit;
}
```
Thought that body styles was omitted to allow for customization, but since I noticed that buttons were not working right in my case I am not certain anymore.

**Comment by StfBauer** [comment]
That is the correct way to do it. Since I don't like to overwrite all the style in things like SharePoint I left out that body piece.

The second part I put in the wrong place 🤦‍♂️

**Comment by gabbsmo** [comment]
Yes that makes sense. Please let me know when your fix is on npm and I should be able to remove my workaround for the buttons.

**Comment by StfBauer** [comment]
Commited a couple of changes the new version goes out today I think.
