### ISSUE TITLE
Command buttons as links

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#154]
**Is your feature request related to a problem? Please describe.**
The CSS styles for `.hoo-buttoncmd` assumes that there is always a `<button>` tag. I have a few cases where they are actually links. 

Example:
**Describe the solution you'd like**

```
<a class="hoo-buttoncmd" href="settings" role="menuitem" tabindex="-1" href="settings" title="Settings">
        <span class="hoo-button-icon"><i class="ms-Icon ms-Icon--Settings" aria-hidden="true"></i></span>
</a>
````

**Describe alternatives you've considered**
To get the right style I currently need to add a button element as a child. While it works, it is not valid HTML.

```
<a class="hoo-buttoncmd" href="settings" role="menuitem" tabindex="-1" href="settings" title="Settings">
    <button type="button" class="hoo-buttoncmd" tabindex="-1">
        <span class="hoo-button-icon"><i class="ms-Icon ms-Icon--Settings" aria-hidden="true"></i></span>
    </button>
</a>
````

**Comment by StfBauer** [comment]
Thanks I will look into this. Was bit distracted over the last couple of weeks but I'll look into this!

**Comment by gabbsmo** [comment]
@StfBauer No worries! Just let me know if you want help.

**Comment by StfBauer** [comment]
Always ;)

**Comment by StfBauer** [comment]
Should work now please check.
