### ISSUE TITLE
Field descriptions not matching Fluent React

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#157]
**Describe the bug**
Field descriptions and validation errors use slightly larger font size in hTWOo, than Fluent React.

**To Reproduce**
1. Compare [Style Guide...](https://lab.n8d.studio/htwoo/htwoo-core/?p=molecules-field)
2. with [Fluent React](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 130

**Additional context**
Logged this as bug on the assumption that Fluent React can be used as a reference implementation for Fluent UI.

**Comment by StfBauer** [comment]
Yeah because all the fonts are off and too small in in Flunet UI React. I could change it but for the sake of accessibility I made them a bit larger.

**Comment by gabbsmo** [comment]
I agree that the example in the style guide is more readable. But in my opinion, the smaller text (0.75rem) used in Fluent React, helps individual fields or options stand out more. With the larger text in hTWOo (0.875rem), everything kind of blends together.  It is easier for me to read the field labels one by one, without having to make an effort to skip the descriptions, if the descriptions are not too close in size. This is of course only my subjective opinion.

I also agree that there are some measurements in Fluent React that I deviate from myself. For example I use 1 rem margin between form field, instead of Fluent React's 15px (what's up with that?).

Example 1 from MetaShare (0.75rem):
![image](https://github.com/user-attachments/assets/734577e0-ce54-479b-ac26-d7eeab8b5c35)

Example 2 from MetaShare (0.875rem):
![image](https://github.com/user-attachments/assets/5d1aa82f-e9ab-433e-bda1-afc6a2ecd711)

Example 3 from Style Guide (repeated molecules):
![image](https://github.com/user-attachments/assets/e334b957-0a8a-4d5c-a723-a16e8940932c)
