### ISSUE TITLE
Creating new React components

### ISSUE THREAD

**Issue by sympmarc** [n8design/htwoo#17]
@mikezimm there are some how-to available on the [documentation page](https://lab.n8d.studio/htwoo/how-to/how-to-spfx-react.html). Have you checked those out. Also, there is a [sample](https://github.com/n8design/htwoo-samples) repo that helps you get started.

_Originally posted by @StfBauer in https://github.com/n8design/htwoo/issues/11#issuecomment-850194003_

@StfBauer - I saw your reply above to @mikezimm about the sample repo. Have you written something up for us to follow to help build out those components? It may be the documentation link above is it, but I want to be sure. I'm game to try using the library soon.

**Comment by StfBauer** [comment]
In the documentation there is a how-to implement with ReactJS:
https://lab.n8d.studio/htwoo/how-to/how-to-spfx-react.html
In the sample repo, there is a complete sample ready to use built with SPFx
https://github.com/n8design/htwoo-samples
+ there is a blog post that basically is just a cross-post from the documentation.

**Comment by juliemturner** [comment]
htwoo-react control released to GA.

I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
