### ISSUE TITLE
_base.scss - incorrect imports version 0.3.0

### ISSUE THREAD

**Issue by juliemturner** [n8design/htwoo#19]
Version 0.3.0

**Describe the bug**
The _base.scss file includes the following imports:

@import '../sass/00-base/atoms/loading/progress';
@import '../sass/00-base/atoms/loading/shimmer';

These paths are incorrect but also, I believe the imports should be included in the _style.scss file instead where they are already correctly referenced, so I believe the fix is to remove them. Currently when importing _base.scss you get a build error because it cannot resolve the paths.

**Comment by StfBauer** [comment]
Thank you for the heads-up that fixed the path issue and published v0.3.1
