### ISSUE TITLE
v0.3.0 build error for htwoo-react

### ISSUE THREAD

**Issue by sympmarc** [n8design/htwoo#20]
**Describe the bug**
Tried to build htwoo-react and got the following error. May be related to #19?
```
ERROR in ./lib/index.js
Module not found: Error: Can't resolve './Base.css' in 'D:\code\htwoo\htwoo-react\lib'
 @ ./lib/index.js 1:0-20

ERROR in ./lib/components/LQDButton/LQDButton.js
Module not found: Error: Can't resolve './LQDButton.css' in 'D:\code\htwoo\htwoo-react\lib\components\LQDButton'
 @ ./lib/components/LQDButton/LQDButton.js 28:0-25
 @ ./lib/components/LQDButton/index.js
 @ ./lib/LQDButton.js
 @ ./lib/index.js

ERROR in ./lib/components/LQDWebPartTitle/LQDWebPartTitle.js
Module not found: Error: Can't resolve './LQDWebPartTitle.css' in 'D:\code\htwoo\htwoo-react\lib\components\LQDWebPartTitle'
 @ ./lib/components/LQDWebPartTitle/LQDWebPartTitle.js 28:0-31
 @ ./lib/components/LQDWebPartTitle/index.js
 @ ./lib/LQDWebPartTitle.js
 @ ./lib/index.js
```
**To Reproduce**
- Open htwoo-react directory in VS code
- `npm -i`

**Expected behavior**
Build succeeds

**Screenshots**
![image](https://user-images.githubusercontent.com/1295627/121932460-e5984880-cd12-11eb-8ae8-1cc0d8de3a3a.png).

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [e.g. chrome, safariNA]
 - Version [v0.3.0]

**Comment by juliemturner** [comment]
The React library is only a framework and not ready for use.

**Comment by sympmarc** [comment]
I figured the answer might be something like that. Should I close this?

**Comment by StfBauer** [comment]
Yes - hTWOo-react is not available yet.
