### ISSUE TITLE
hoo-doccard styling issues with htwoo-react components

### ISSUE THREAD

**Issue by bcameron1231** [n8design/htwoo#28]
**Describe the bug**
This may have come back from a previous bug?  https://github.com/n8design/htwoo/issues/21

Creating a document card using the HooCardImage, HooCardLocation, HooCardTitle components has a styling issue when the Location/Title values are really long.

What happens is, the HooCardImage doesn't grow with the container when the card properties push the container width

**To Reproduce**

Given that no HooDocumentCard control exists yet, create a document card following the Pattern Lab documentation, but use the new htwoo-react components for the image/location/title

1. Document Card HTML
```
 <div className={`hoo-doccard`}>
        <HOOCardImage imageSource={<pathToImage>}/>
        <HOOCardLocation location="https://northpoleindustries.sharepoint.com/sites/WorkshopTemplate"/>
        <HOOCardTitle title="Workshop Template" />
    </div>
```

**Expected behavior**
When loading a DocumentCard, the location/title fields should either wrap/ellipsis or the HooCardImage should grow the container as these properties get longer.

**Screenshots**
![image](https://user-images.githubusercontent.com/7944457/144312796-8248b1ee-1fa4-4a36-b155-893e21196376.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: All

**Comment by juliemturner** [comment]
Bug fixed in version 0.0.0-pre-alpha-22
